# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_protected/pic_protected.xci
# IP: The module: 'pic_protected' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_protected/pic_protected_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pic_protected'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_protected/pic_protected.xci
# IP: The module: 'pic_protected' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_protected/pic_protected_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pic_protected'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
