# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA/snake_basys3/snake_basys3.cache/wt [current_project]
set_property parent.project_path D:/FPGA/snake_basys3/snake_basys3.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo d:/FPGA/snake_basys3/snake_basys3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/FPGA/snake_basys3/coe/protected.coe
add_files D:/FPGA/snake_basys3/coe/slowly.coe
add_files D:/FPGA/snake_basys3/coe/grade.coe
add_files d:/FPGA/snake_basys3/320.coe
read_verilog -library xil_defaultlib {
  D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/imports/src/Seg_Display.v
  D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/imports/src/VGA_Control.v
  D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/imports/src/apple_generator.v
  D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/imports/src/buttons.v
  D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/imports/src/clk_unit.v
  D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/imports/src/clock.v
  D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/imports/src/game_status_control.v
  D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/imports/src/interface_display.v
  D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/imports/src/reward_display.v
  D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/imports/src/reward_information.v
  D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/imports/src/reward_logic.v
  D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/imports/src/reward_random_generator.v
  D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/imports/src/snake_moving.v
  D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/imports/src/vga_display.v
  D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/imports/src/top_greedy_snake.v
}
read_ip -quiet D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_protected/pic_protected.xci
set_property used_in_implementation false [get_files -all d:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_protected/pic_protected_ooc.xdc]

read_ip -quiet D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_slowly/pic_slowly.xci
set_property used_in_implementation false [get_files -all d:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_slowly/pic_slowly_ooc.xdc]

read_ip -quiet D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_grade/pic_grade.xci
set_property used_in_implementation false [get_files -all d:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_grade/pic_grade_ooc.xdc]

read_ip -quiet D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_snake/pic_snake.xci
set_property used_in_implementation false [get_files -all d:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_snake/pic_snake_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FPGA/snake_basys3/snake_basys3.srcs/constrs_1/imports/xdc/snake_basys3_xc.xdc
set_property used_in_implementation false [get_files D:/FPGA/snake_basys3/snake_basys3.srcs/constrs_1/imports/xdc/snake_basys3_xc.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top_greedy_snake -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_greedy_snake.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_greedy_snake_utilization_synth.rpt -pb top_greedy_snake_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
