# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_snake/pic_snake.xci
# IP: The module: 'pic_snake' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_snake/pic_snake_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pic_snake'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_snake/pic_snake.xci
# IP: The module: 'pic_snake' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/snake_basys3/snake_basys3.srcs/sources_1/ip/pic_snake/pic_snake_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pic_snake'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
